# version: '2.2'
# services:

#     minio:
#         image: minio/minio
#         container_name: minio
#         ports:
#           - 9000:9000
#           - 9001:9001
#         entrypoint: ["minio", "server", "/data,","--console-address",":9001"]


#     trino:
#         image: trinodb/trino:358
#         container_name: trino